tianxia/apps/users/urls.py
#@Author   ：Htojk
#@Time     :2018/9/27  19:12
#@Software :PyCharm

from django.conf.urls import re_path
from .  import views

app_name='users'
urlpatterns = [
    re_path(r'^$',views.Index_view,name='index'),
    re_path(r'^login/$',views.Login_view,name='login'),
    re_path(r'^logout/$',views.Logout_view,name='logout'),
    re_path(r'^register/$',views.Register_view,name='register'),
    re_path(r'^user_center/$',views.User_center_view,name='user_center'),
    # re_path(r'^artical_test/$',views.Artical_test_view,name='artical_test'),
    re_path(r'^pictures_show/(\d)/$',views.Pictures_show_details_view,name='pictures_show_details'),
    re_path(r'^changeMessage/$',views.Change_user_message_view,name='change_user_message'),
    re_path(r'^changePassword/$',views.Change_password_view,name='change_password'),
]

tianxia/tianxia/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from .import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('apps.users.urls'))
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tianxia/apps/connection/models.py
from django.db import models

# Create your models here.

tianxia/apps/index/models.py
from django.db import models
from apps.users import models as users_models
from ckeditor.fields import RichTextField
# Create your models here.

class show_pictures_index(models.Model):
    id=models.IntegerField(primary_key=True)
    description=models.TextField()
    picture=models.ImageField(upload_to='show_pictures_index')
    artical=models.ForeignKey(users_models.ArticalDetails,on_delete=models.DO_NOTHING,default=None)
    class Meta:
        verbose_name_plural='首页轮播图'
        db_table='show_pictures_index'

class Book(models.Model):
    name=models.CharField(max_length=40,verbose_name='书名')
    author=models.ForeignKey(users_models.User,on_delete=models.CASCADE)
    status=models.CharField(max_length=20,choices=(('update','连载中'),('finished','完结')))
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural='书籍'

class Book_every_colomn(models.Model):
    index_num=models.IntegerField(primary_key=True,verbose_name='章节序号')
    title=models.CharField(max_length=50,verbose_name='章节名称')
    book=models.ForeignKey(Book,on_delete=models.CASCADE)
    content=RichTextField()
    create_time=models.DateTimeField(auto_now_add=True)
    read_num=models.IntegerField(default=0)
    get_good=models.IntegerField(default=0)
    def __str__(self):
        return self.title
    class Meta:
        verbose_name_plural='章节详情'

class Book_colomn_details(models.Model):
    index_num=models.IntegerField(primary_key=True,verbose_name='章节序号')
    title=models.CharField(max_length=50,verbose_name='章节名称')
    book=models.ForeignKey(Book,on_delete=models.CASCADE)
    content=RichTextField()
    create_time=models.DateTimeField(auto_now_add=True)
    read_num=models.IntegerField(default=0)
    get_good=models.IntegerField(default=0)
    def __str__(self):
        return self.title
    class Meta:
        verbose_name_plural='章节详情'

tianxia/apps/users/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
# Create your models here.
class OrdernaryUser(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    nickname=models.CharField(blank=True,null=True,max_length=50)
    def __str__(self):
        return self.nickname
    class Meta:
        verbose_name='普通会员表'
        verbose_name_plural=verbose_name

class ArticalType(models.Model):
    type=models.CharField(max_length=10,choices=(('xiaoshuo','小说'),('sanwen','散文'),('shige','诗歌'),('shuping','书评')),verbose_name='文章分类')
    def __str__(self):
        return self.type
    class Meta:
        verbose_name_plural='文章分类'

class ArticalDetails(models.Model):
    title=models.CharField(max_length=50,verbose_name='标题')
    type=models.ForeignKey(ArticalType,on_delete=models.CASCADE,verbose_name='类别')
    author=models.ForeignKey(OrdernaryUser,on_delete=models.CASCADE,verbose_name='作者')
    read_num=models.IntegerField(default=0,verbose_name='浏览量')
    create_time=models.DateTimeField(auto_now_add=True)
    content=RichTextField()
    def __str__(self):
        return self.title
    class Meta:
        verbose_name_plural='文章'

tianxia/apps/users/forms.py
#@Author   ：Htojk
#@Time     :2018/10/8  19:57
#@Software :PyCharm

from django.contrib.auth.forms import UserCreationForm,UserChangeForm,PasswordChangeForm
from django.contrib.auth.models import User
from django import forms


class SelfDefineUser(UserCreationForm):
    昵称=forms.CharField(max_length=50,required=False)
    class Meta:
        model=User
        fields=('username','password1','password2','email','昵称')

class SelfDefineChangeMessage(UserChangeForm):
    昵称 = forms.CharField(max_length=50, required=False)
    class Meta:
        model = User
        fields = ('username', 'password', 'email', '昵称')

tianxia/apps/connection/views.py
from django.shortcuts import render

# Create your views here.

tianxia/apps/index/views.py
from django.shortcuts import render

# Create your views here.

tianxia/apps/users/views.py
from django.shortcuts import render,render_to_response,redirect
from django.contrib.auth import login,logout,authenticate
from . import forms,models
from django.contrib.auth.decorators import login_required
from apps.index.models import show_pictures_index
# Create your views here.


def Index_view(request):
    all_articals=show_pictures_index.objects.all()
    content={'articals':all_articals}
    return render(request,'index.html',content)


def Login_view(request):
    if (request.method=='POST'):
        user=authenticate(request,username=request.POST['username'],password=request.POST['password'])
        if(user is None):
            return render(request,'login.html',{"errors":'用户名或者密码错误'})
        else:
            login(request,user)
            return redirect('users:index')
    else:
        return render(request,'login.html')

def Logout_view(request):
    logout(request)
    return redirect('users:index')

def Register_view(request):
    if (request.method=='POST'):
        register_form=forms.SelfDefineUser(request.POST)
        if (register_form.is_valid()):
            register_form.save()
            user=authenticate(username=register_form.cleaned_data['username'],password=register_form.cleaned_data['password1'])
            user.email = register_form.cleaned_data['email']
            models.OrdernaryUser(user=user, nickname=register_form.cleaned_data['昵称']).save()
            login(request,user)
            return redirect('users:index')
    else:
        register_form=forms.SelfDefineUser()
    content={'register_form':register_form}
    return render(request,'register.html',content)

@login_required(login_url='users:login')
def User_center_view(requets):
    content={'user':requets.user}
    return render(requets,'user_center.html',content)
@login_required(login_url='users:login')
def Change_user_message_view(request):
    if request.method=="POST":
        change_message_form=forms.SelfDefineChangeMessage(request.POST,instance=request.user)
        if change_message_form.is_valid():
            change_message_form.save()
            request.user.ordernaryuser.nickname=change_message_form.cleaned_data['昵称']
            request.user.ordernaryuser.save()
            return redirect("users:user_center")
    else:
        change_message_form=forms.SelfDefineChangeMessage(instance=request.user)
    content={"change_message_form":change_message_form,'user':request.user,'ordernaryuser':request.user.ordernaryuser}
    return render(request,'change_message.html',content)

@login_required(login_url='users:login')
def Change_password_view(request):
    if request.method=="POST":
        change_password_form=forms.PasswordChangeForm(data=request.POST,user=request.user)
        if change_password_form.is_valid():
            change_password_form.save()
            return redirect("users:login")
    else:
        change_password_form=forms.PasswordChangeForm(user=request.user)
    content={"change_password_form":change_password_form,'user':request.user,}
    return render(request,'change_password.html',content)

def Artical_test_view(request):
    return render(request,'artical_details.html')

def Pictures_show_details_view(request,id):
    all_message=show_pictures_index.objects.filter(id=id)
    artical=all_message[0].artical
    content={'artical':artical,'id':id}
    return render(request,'artical_details.html',content)

tianxia/templates/artical_details.html
{% extends 'base.html' %}
{% block main %}
    <div class="content">
        <div class="content_details">
            <h4>{{ artical.title }}</h4>
            <p>作者：{{ artical.author }}&nbsp;&nbsp;&nbsp;&nbsp;更新时间：{{ artical.create_time }}&nbsp;&nbsp;&nbsp;&nbsp;阅读量：{{ artical.read_num }}</p>
            <hr>
            {{ artical.content|safe }}
        </div>
        <hr>
        <hr>
        <div class="communicate">
            <a href="">打赏</a>
            <a href="">投月票</a>
            <a href="">点赞</a>
            <a href="">评论</a>
            <a href="">下一篇：</a>
            <a href="">上一篇：</a>
        </div>
    </div>


    <style>
        .content{
            margin:0 auto;
            width: 840px;
            height: auto;
            border: 2px solid lightslategrey;
        }
        .content_details{
            margin: 0px auto;
            margin-top: 20px;
            width: 780px;
            height: auto;
        }
        .communicate{
            margin-bottom:10px;
            text-align: center;
        }
    </style>
{% endblock %}


tianxia/templates/base.html
{% load  staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <script src="{% static 'jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
    <script href="{% static 'jquery-1.12.4.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'base/css/base.css' %}">
</head>
<body>
<div class="container-fluid">
    <div class="header">
        <span class="glyphicon glyphicon-cloud header_title" aria-hidden="true">天下文学，聚四海彦哲，会八方英才!!</span>
        <span class="header_others">
            {% if user.is_authenticated %}
                <a>欢迎你！{{ user.username }}</a>
                <a href="{% url 'users:logout' %}">登出</a>
            {% else %}
                <a>欢迎文友回家</a>&nbsp;
                <a href="{% url 'users:login' %}">登录</a>&nbsp;
                <a href="{% url 'users:register' %}">注册</a>&nbsp;
            {% endif %}

{#              <a>#}
{#                  <span class="glyphicon glyphicon-cloud header_title" aria-hidden="true">用户001</span>#}
{#              </a>#}
        </span>
    </div>
</div>
<div class="container">
    <div class="header_show">
        <span class="website_title"><h1>天下文学交流网站</h1></span>
    </div>
</div>
<div class="container">
    <ul class="nav nav-tabs">
        <li role="presentation" class="option"><a href="{% url 'users:index' %}">首页</a></li>
        <li role="presentation" class="option"><a href="/artical_test/">小说</a></li>
        <li role="presentation" class="option"><a href="#">诗歌</a></li>
        <li role="presentation" class="option"><a href="#">散文</a></li>
        <li role="presentation" class="option"><a href="#">书评</a></li>
        <li role="presentation" class="option"><a href="/user_center/">个人中心</a></li>
    </ul>
</div>{% block main %}


{% endblock %}
<hr>
<div class="container-fluid">
    <div class="bottom">
        <div class="bottom_inner">
            <p>天下文学团队负责运营维护&nbsp;|&nbsp;联系方式：XXXXXXXX </p>
            <p>本网站有部分内容来自互联网，如媒体、公司、企业或个人对该部分主张知识产权，请来电或致函告之，本网站将采取适当措施，否则，与之有关的知识产权纠纷本网站不承担任何责任。</p>
            <p></p>
        </div>
    </div>
</div>
</body>
<style>
    ul,li,body{
        margin: 0;
        padding:0;
    }
    ul,li{
        list-style: none;
    }
    .header{
        background: linear-gradient(135deg,#0B5E9E 0,#F8626E 100%);
        width: 100%;
        height: 40px;
        border: 1px solid red;
    }
    .header_title{
        font-size: 12px;
        margin-left: 20px;
        line-height: 40px;
        color: white;
    }
    .header_others{
        float: right;
        line-height: 40px;
        margin-right: 20px;
    }
    .header_others a{
        text-outline: none;
        color: white;
        font-size: 13px;
    }
    .header_show{
        background-image: url("{% static 'base/imgs/header_bg.jpg' %}");
        height: 80px;
        width: 1145px;
        border: 1px solid red;
    }

    .website_title{
        line-height: 80px;
        text-align: center;
    }
    .bottom{
        height: 150px;
        background: #f6f6f6;
        width: 100%;
        text-align: center;
    }
    .bottom_inner{
        padding-top: 20px;
    }
    .bottom_inner p{
        font-size: 14px;
        line-height: 40px;
    }
</style>

</html>

tianxia/templates/change_message.html
{% extends 'base.html' %}
{% block title %}
    注册
{% endblock %}

{% block main %}
    <div class="container">
        {{ change_message_form.errors }}
        <div class="body">
            <h1>修改个人信息</h1>
            <form action="" method="post">
{#                {{ register_form }}#}
                {% csrf_token %}
                 <div class="body_left">
                    <ul>
                        <li>用户名</li>
                        <li>昵称</li>
                        <li>邮箱</li>
                    </ul>
                </div>
                <div class="body_mid">
                    <ul>
                        <li><input type="text" name="username" value="{{ user.username }}"></li>
                        <li><input type="text" name="昵称" value="{{ ordernaryuser.nickname }}"></li>
                        <li><input type="email" name="email" value="{{ user.email }}"></li>
                    </ul>
                </div>
                <div class="body_right">
                    <ul>
                        <li><p></p></li>
                        <li><p></p></li>
                        <li><p></p></li>
                    </ul>
                </div>
                <button class="btn">确认修改</button>
            </form>

        </div>
    </div>

    <style>
        .body{
            width: 900px;
            height: 800px;
            margin: 0 auto;
            border: 1px solid black;
            text-align: center;
        }

        .body_left{
            float:left;
            width: 100px;
            height: 500px;
            border: 1px solid red;
            margin-left: 30px;
        }

        .body_left li{
            width: 90px;
            height: 40px;
            border: 1px solid blue;
            margin-top: 30px;
            font-size: 20px;
            line-height: 40px;
            text-align: right;
        }
        .body_mid{
            float:left;
            width: 400px;
            height: 500px;
            border: 1px solid green;
            margin-left: 10px;
        }
        .body_mid li{
            width: 350px;
            height: 40px;
            margin-top: 30px;
            font-size: 20px;
            line-height: 40px;
            text-align: left;
        }
        .body_mid input{
            width: 350px;
        }
        .body_right{
            float:left;
            width: 300px;
            height: 500px;
            border: 1px solid green;
            margin-left: 10px;
        }
        .body_right li{
            width: 260px;
            height: 40px;
            margin-top: 30px;
            text-align: left;
            border: 1px solid black;

        }
    </style>
{% endblock %}


tianxia/templates/change_password.html
{% extends 'base.html' %}
{% block title %}
    注册
{% endblock %}

{% block main %}
    <div class="container">
        <form action="" method="post">
            {% csrf_token %}
            {{ change_password_form.as_p }}
            {{ change_password_form.errors }}
            <button>确认修改</button>

        </form>

    </div>

{% endblock %}

tianxia/templates/login.html
{% extends 'base.html' %}
{% load  static %}


{% block title %}
    登录
{% endblock %}


{% block main %}
<div class="container">
    <div class="login_body">
        <div class="body_left">
            <form action="" method="post">
                {% csrf_token %}
                <h1>用户登录</h1>
                <ul>
                    <li>账号：<input type="text" name="username"></li>
                    <li>密码：<input type="password" name="password"></li>
                    <li><button>登录</button></li>
                </ul>
            </form>
            <div class="errors">
                {{ errors }}
            </div>
            <div class="to_index"><a href="{% url 'users:index' %}">返回首页</a></div>
        </div>
        <div class="body_right">

            <h1>用户注册</h1>
            <p>还没有账户？</p>
            <p><a href="">点我注册</a></p>
        </div>
    </div>

</div>
    <style>
        .login_body{
            margin: 0 auto;
            width: 804px;
            height: 500px;
            border: 1px solid lightgrey;
        }
        .body_left{
            float:left;
            width: 600px;
            height: 100%;
            border-right: 1px solid lightgrey;
        }
        .body_left h1,.body_right h1{
            margin-top: 100px;
            text-align: center;
        }
        .body_left ul{
            margin-top: 30px;
            text-align: center;
        }
        .body_left li{
            margin-top: 20px;
        }
        .body_right{
            float: left;
            width: 200px;
            height: 100%;
            text-align: center;
        }
        .to_index{
            margin-top: 10px;
            margin-left: 450px;
        }
        .errors{
            width: 400px;
            height: 100px;
            margin: 0 auto;
            margin-top: 50px;
            text-align: center;
        }
    </style>
{% endblock %}

tianxia/templates/register.html
{% extends 'base.html' %}
{% block title %}
    注册
{% endblock %}

{% block main %}
    <div class="container">
        {{ register_form.errors }}
        <div class="body">
            <h1>用户注册</h1>
            <form action="" method="post">
{#                {{ register_form }}#}
                {% csrf_token %}
                 <div class="body_left">
                    <ul>
                        <li>用户名</li>
                        <li>昵称</li>
                        <li>邮箱</li>
                        <li>密码</li>
                        <li>确认密码</li>
                        <li>验证码</li>
                    </ul>
                </div>
                <div class="body_mid">
                    <ul>
                        <li><input type="text" name="username"></li>
                        <li><input type="text" name="nickname"></li>
                        <li><input type="email" name="email"></li>
                        <li><input type="password" name="password1" required id='id_password1'></li>
                        <li><input type="password" name="password2" required id='id_password2'></li>
                        <li><input type='text' name="identifyingcode"></li>
                    </ul>
                </div>
                <div class="body_right">
                    <ul>
                        <li><p></p></li>
                        <li><p></p></li>
                        <li><p>不能与其他人他太相似，不少于八位，不能全部为数字</p></li>
                        <li><p>请输入与上面相同的密码</p></li>
                        <li><p></p></li>
                        <li><p></p></li>
                    </ul>
                </div>
                <button class="btn">确认注册</button>
            </form>

        </div>
    </div>

    <style>
        .body{
            width: 900px;
            height: 800px;
            margin: 0 auto;
            border: 1px solid black;
            text-align: center;
        }

        .body_left{
            float:left;
            width: 100px;
            height: 500px;
            border: 1px solid red;
            margin-left: 30px;
        }

        .body_left li{
            width: 90px;
            height: 40px;
            border: 1px solid blue;
            margin-top: 30px;
            font-size: 20px;
            line-height: 40px;
            text-align: right;
        }
        .body_mid{
            float:left;
            width: 400px;
            height: 500px;
            border: 1px solid green;
            margin-left: 10px;
        }
        .body_mid li{
            width: 350px;
            height: 40px;
            margin-top: 30px;
            font-size: 20px;
            line-height: 40px;
            text-align: left;
        }
        .body_mid input{
            width: 350px;
        }
        .body_right{
            float:left;
            width: 300px;
            height: 500px;
            border: 1px solid green;
            margin-left: 10px;
        }
        .body_right li{
            width: 260px;
            height: 40px;
            margin-top: 30px;
            text-align: left;
            border: 1px solid black;

        }
    </style>
{% endblock %}


tianxia/templates/test1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <ul>
        <li>1</li>
        <li>2</li>
        <li>3</li>
        <li>4</li>
        <li>5</li>
    </ul>



</body>
<style>
    ul li{
        float:left;

    }


</style>
</html>

tianxia/templates/user_center.html
{% extends 'base.html' %}

{% block main %}
    <div class="content">
        <h1>个人中心</h1>
        <div class="box">
            <a href="/changeMessage/">编辑个人信息</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="/changePassword/">修改密码</a>
        </div>
        <hr>
        <hr>
        <h4 class="little_title">基本信息</h4>
        <div class="basic_message box">
            <ul>
                <li>用户名：{{ user.username }}</li>
                <li>昵称：{{ user.ordernaryuser.nickname }}</li>
                <li>邮箱：{{ user.email }}</li>
                <li>会员等级：1级</li>
                <li>所属团队：天下文学</li>
            </ul>
        </div>
        <hr>
        <h4 class="little_title">文章列表</h4>
        <div class="articals_message box">
        </div>
    </div>
    <style>
        .content{
            width:800px;
            height: 1000px;
            border: 1px solid red;
            margin:0  auto;
        }
        h1,h4{
            text-align: center;
        }
        .box{
            width: 600px;
            margin: 0 auto;
            {#border: 1px solid green;#}
        }
        .basic_message{
            height: auto
        }
        .basic_message ul{
            margin-left: 180px;
            margin-top: 30px;
            text-align: left;
        }
        .basic_message li{
            margin-top: 15px;

        }
        .articals_message{
            height: auto;
        }

    </style>
{% endblock %}